version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: counter-api
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - db-network

  db:
    build:
      context: ./db-config
      dockerfile: Dockerfile
    container_name: counter-db
    ports:
      - "5432:5432"
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
